CREATE TABLE Administrator(
	AdminID CHAR(3) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Password VARCHAR(11) DEFAULT 12345678,
);


CREATE TABLE StoreHouse(
	StHoID CHAR(3) PRIMARY KEY,
	StoreHouseName NVARCHAR(100) NOT NULL,
	Area INT CHECK(Area>0) NOT NULL,
);


CREATE TABLE Operator(
	OperID CHAR(3) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Password VARCHAR(11) DEFAULT 12345678,
	AdminID CHAR(3) FOREIGN KEY
		REFERENCES Administrator(AdminID),
	StHoID CHAR(3) FOREIGN KEY
		REFERENCES StoreHouse(StHoID),
);


CREATE TABLE Supplier(
	SuppID CHAR(3) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Password VARCHAR(11) DEFAULT 12345678,
	AdminID CHAR(3) FOREIGN KEY
		REFERENCES Administrator(AdminID),
);


CREATE TABLE Deliveryman(
	DeliID CHAR(3) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Password VARCHAR(11) DEFAULT 12345678,
	AdminID CHAR(3) FOREIGN KEY
		REFERENCES Administrator(AdminID),
);


CREATE TABLE Customer(
	CustID CHAR(5),
		CONSTRAINT CustomerKey PRIMARY KEY(CustID),
	Idnumber CHAR(18)
		CONSTRAINT CustomerC1 UNIQUE 
		CONSTRAINT CustomerC2 NOT NULL,
	Name NVARCHAR(100)
		CONSTRAINT CustomerC3 NOT NULL,
	Password VARCHAR(11)
		CONSTRAINT CustomerC4 DEFAULT 12345678,
	Email VARCHAR(50)
		CONSTRAINT CustomerC5 UNIQUE,
	Address NVARCHAR(100),
	Telephone CHAR(11)
		CONSTRAINT CustomerC6 UNIQUE,
	Sex NCHAR(1)
		CONSTRAINT CustomerC7 CHECK(Sex IN ('男','女')),
);


CREATE TABLE Book(
	ISBN CHAR(13),
		CONSTRAINT BookKey PRIMARY KEY(ISBN),
	BookName NVARCHAR(100)
		CONSTRAINT BookC1 NOT NULL,
	Category NVARCHAR(100),
	Author NVARCHAR(100),
	Publisher NVARCHAR(100),
	PubDate DATE,
	Discount NUMERIC(3,2)
		CONSTRAINT BookC2 CHECK(Discount>0 AND Discount<=1)
		CONSTRAINT BookC3 DEFAULT 1,
	SellPrice NUMERIC(6,2)
		CONSTRAINT BookC4 CHECK(SellPrice>0),
	PurchasePrice NUMERIC(6,2)
		CONSTRAINT BookC5 CHECK(PurchasePrice>0),
	StHoID CHAR(3) 
		CONSTRAINT BookC6 NOT NULL,
		CONSTRAINT BookC7 FOREIGN KEY(StHoID) REFERENCES StoreHouse(StHoID),
	Inventory INT
		CONSTRAINT BookC8 NOT NULL
		CONSTRAINT BookC9 CHECK(Inventory >= 0),
);


CREATE TABLE Orders(
	OrderID CHAR(10) PRIMARY KEY,
	OrderDate TIMESTAMP,
	DeliveryAddress NVARCHAR(100) NOT NULL,
	CustID CHAR(5) FOREIGN KEY
		REFERENCES Customer(CustID),
	DeliID CHAR(3) FOREIGN KEY
		REFERENCES Deliveryman(DeliID),
);


CREATE TABLE OrderElem(
	OrderID CHAR(10),
	ISBN CHAR(13),
	OrderQuantity INT CHECK(OrderQuantity>0) NOT NULL,
	FOREIGN KEY(OrderID) REFERENCES Orders(OrderID),
	FOREIGN KEY(ISBN) REFERENCES Book(ISBN),
	PRIMARY KEY(OrderID, ISBN),
);


CREATE TABLE Supply(
	SuppID CHAR(3),
	ISBN CHAR(13),
	SuppDate DATE,
	SupplyQuantity INT CHECK(SupplyQuantity>0) NOT NULL,
	PRIMARY KEY(SuppID, ISBN, SuppDate),
	FOREIGN KEY(SuppID) REFERENCES Supplier(SuppID),
	FOREIGN KEY(ISBN) REFERENCES Book(ISBN),
);
